#!/bin/bash -l
#SBATCH --job-name=sbatchtest
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=2
#SBATCH --mem=4gb
#SBATCH --time=0:20:00

#SBATCH --mail-type=ALL
#SBATCH --mail-user=ley015@csiro.au

module load fastqc/0.11.8 


fastqc --threads 64 /OSM/CBR/AF_DATASCHOOL/input/2019-04-12_Transcritome/CA73YANXX_8_161220_BPO--000_Other_TAAGGCGA-CTCTCTAT_R_161128_SHADIL_LIB2500_M002_R1.fastq.gz -o /OSM/CBR/AF_DATASCHOOL/output/epl/fastqc_results2/

