#!/bin/bash -l
#SBATCH --job-name=sbatchtest
#SBATCH -N 64
#SBATCH -n 64
#SBATCH --ntasks-per-node=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ley015@csiro.au
#SBATCH --time=2:00:00

module load fastqc/0.11.8


fastqc --threads 64 /OSM/CBR/AF_DATASCHOOL/input/2019-04-12_Transcritome/*.fastq.gz -o /OSM/CBR/AF_DATASCHOOL/output/epl/fastqc_results2/

