#!/bin/bash -l
#SBATCH --job-name=test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=4gb
#SBATCH --time=0:10:00

#SBATCH --mail-type=ALL
#SBATCH --mail-user=ley015@csiro.au

module load fastq
fastqc /OSM/CBR/AF_DATASCHOOL/input/2019-04-12_Transcritome/*.fastq.gz 
-o '/OSM/CBR/AF_DATASCHOOL/output/epl/fastqc_results2/'
sleep 120
