#!/bin/bash -l
#SBATCH --job-name=looptest
#SBATCH --ntasks=64
#SBATCH --mem=1gb
#SBATCH --time=0:02:00

##SBATCH --mail-type=ALL
##SBATCH --mail-user=ley015@csiro.au


#load the fastqc module so we can run it.
module load fastqc


inputdir=/OSM/CBR/AF_DATASCHOOL/input/2019-04-12_Transcritome
outputdir=/OSM/CBR/AF_DATASCHOOL/output/epl/results



for filename in $inputdir/*.fastq.gz
do
  echo $filename
  fastqc $filename -o $outputdir
  sbatch ./singlefile $filename $outputdir
done
