#!/bin/bash -l
#SBATCH --job-name=test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=4
#SBATCH --mem=4gb
#SBATCH --time=2:00:00

#SBATCH --mail-type=ALL
#SBATCH --mail-user=mcl226@csiro.au

module load fastqc/0.11.8
fastqc /OSM/CBR/AF_DATASCHOOL/input/2019-04-12_Transcritome/*.fastq.gz -o /OSM/CBR/AF_DATASCHOOL/output/gmcl/FQCresults3/

